# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Dropbox\Projects\Pioneer_Kit_Shield\Firmware\BLE_To_RPi\BLE_To_RPi.cydsn\BLE_To_RPi.cyprj
# Date: Mon, 11 Dec 2017 22:01:20 GMT
#set_units -time ns
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFClk} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyFLL} -period 10.416666666666666 -waveform {0 5.20833333333333} [list [get_pins {ClockBlock/fll}]]
create_clock -name {CyHFClk0} -period 10.416666666666666 -waveform {0 5.20833333333333} [list [get_pins {ClockBlock/hfclk_0}]]
create_clock -name {CyFastClk} -period 10.416666666666666 -waveform {0 5.20833333333333} [list [get_pins {ClockBlock/fastclk}]]
create_clock -name {CyPeriClk} -period 10.416666666666666 -waveform {0 5.20833333333333} [list [get_pins {ClockBlock/periclk}]]
create_generated_clock -name {CySlowClk} -source [get_pins {ClockBlock/periclk}] -edges {1 2 3} [list [get_pins {ClockBlock/slowclk}]]
create_generated_clock -name {CapSense_ModClk} -source [get_pins {ClockBlock/periclk}] -edges {1 255 511} [list [get_pins {ClockBlock/ff_div_43}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/periclk}] -edges {1 3 5} [list [get_pins {ClockBlock/ff_div_11}]]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/periclk}] -edges {1 3 5} [list [get_pins {ClockBlock/ff_div_12}]]
create_generated_clock -name {Clock_3} -source [get_pins {ClockBlock/periclk}] -edges {1 3 5} [list [get_pins {ClockBlock/ff_div_13}]]
create_clock -name {CyPeriClk_App} -period 10.416666666666666 -waveform {0 5.20833333333333} [list [get_pins {ClockBlock/periclk_App}]]
create_clock -name {CyHFClk1} -period 10.416666666666666 -waveform {0 5.20833333333333} [list [get_pins {ClockBlock/hfclk_1}]]
create_clock -name {CyHFClk2} -period 10.416666666666666 -waveform {0 5.20833333333333} [list [get_pins {ClockBlock/hfclk_2}]]
create_clock -name {CyHFClk3} -period 10.416666666666666 -waveform {0 5.20833333333333} [list [get_pins {ClockBlock/hfclk_3}]]
create_clock -name {CyHFClk4} -period 10.416666666666666 -waveform {0 5.20833333333333} [list [get_pins {ClockBlock/hfclk_4}]]
create_clock -name {CyIMO} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/imo}]]


# Component constraints for C:\Dropbox\Projects\Pioneer_Kit_Shield\Firmware\BLE_To_RPi\BLE_To_RPi.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Dropbox\Projects\Pioneer_Kit_Shield\Firmware\BLE_To_RPi\BLE_To_RPi.cydsn\BLE_To_RPi.cyprj
# Date: Mon, 11 Dec 2017 22:01:18 GMT
