/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_Red */
#define Pin_Red_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Red_0_INBUF_ENABLED 0u
#define Pin_Red_0_INIT_DRIVESTATE 1u
#define Pin_Red_0_INIT_MUXSEL 9u
#define Pin_Red_0_INPUT_SYNC 2u
#define Pin_Red_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Red_0_NUM 3u
#define Pin_Red_0_PORT GPIO_PRT0
#define Pin_Red_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Red_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_Red_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Red_INBUF_ENABLED 0u
#define Pin_Red_INIT_DRIVESTATE 1u
#define Pin_Red_INIT_MUXSEL 9u
#define Pin_Red_INPUT_SYNC 2u
#define Pin_Red_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Red_NUM 3u
#define Pin_Red_PORT GPIO_PRT0
#define Pin_Red_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Red_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_Blue */
#define Pin_Blue_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Blue_0_INBUF_ENABLED 0u
#define Pin_Blue_0_INIT_DRIVESTATE 1u
#define Pin_Blue_0_INIT_MUXSEL 8u
#define Pin_Blue_0_INPUT_SYNC 2u
#define Pin_Blue_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Blue_0_NUM 1u
#define Pin_Blue_0_PORT GPIO_PRT11
#define Pin_Blue_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Blue_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_Blue_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Blue_INBUF_ENABLED 0u
#define Pin_Blue_INIT_DRIVESTATE 1u
#define Pin_Blue_INIT_MUXSEL 8u
#define Pin_Blue_INPUT_SYNC 2u
#define Pin_Blue_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Blue_NUM 1u
#define Pin_Blue_PORT GPIO_PRT11
#define Pin_Blue_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Blue_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_Green */
#define Pin_Green_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Green_0_INBUF_ENABLED 0u
#define Pin_Green_0_INIT_DRIVESTATE 1u
#define Pin_Green_0_INIT_MUXSEL 8u
#define Pin_Green_0_INPUT_SYNC 2u
#define Pin_Green_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Green_0_NUM 1u
#define Pin_Green_0_PORT GPIO_PRT1
#define Pin_Green_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Green_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_Green_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Green_INBUF_ENABLED 0u
#define Pin_Green_INIT_DRIVESTATE 1u
#define Pin_Green_INIT_MUXSEL 8u
#define Pin_Green_INPUT_SYNC 2u
#define Pin_Green_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Green_NUM 1u
#define Pin_Green_PORT GPIO_PRT1
#define Pin_Green_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Green_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Csh */
#define CapSense_Csh_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Csh_0_INBUF_ENABLED 0u
#define CapSense_Csh_0_INIT_DRIVESTATE 1u
#define CapSense_Csh_0_INIT_MUXSEL 0u
#define CapSense_Csh_0_INPUT_SYNC 2u
#define CapSense_Csh_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Csh_0_NUM 2u
#define CapSense_Csh_0_PORT GPIO_PRT7
#define CapSense_Csh_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Csh_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Csh_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Csh_INBUF_ENABLED 0u
#define CapSense_Csh_INIT_DRIVESTATE 1u
#define CapSense_Csh_INIT_MUXSEL 0u
#define CapSense_Csh_INPUT_SYNC 2u
#define CapSense_Csh_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Csh_NUM 2u
#define CapSense_Csh_PORT GPIO_PRT7
#define CapSense_Csh_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Csh_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Sns */
#define CapSense_Sns_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_0_INBUF_ENABLED 0u
#define CapSense_Sns_0_INIT_DRIVESTATE 1u
#define CapSense_Sns_0_INIT_MUXSEL 0u
#define CapSense_Sns_0_INPUT_SYNC 2u
#define CapSense_Sns_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_0_NUM 1u
#define CapSense_Sns_0_PORT GPIO_PRT8
#define CapSense_Sns_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_1_INBUF_ENABLED 0u
#define CapSense_Sns_1_INIT_DRIVESTATE 1u
#define CapSense_Sns_1_INIT_MUXSEL 0u
#define CapSense_Sns_1_INPUT_SYNC 2u
#define CapSense_Sns_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_1_NUM 2u
#define CapSense_Sns_1_PORT GPIO_PRT8
#define CapSense_Sns_1_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_2_INBUF_ENABLED 0u
#define CapSense_Sns_2_INIT_DRIVESTATE 1u
#define CapSense_Sns_2_INIT_MUXSEL 0u
#define CapSense_Sns_2_INPUT_SYNC 2u
#define CapSense_Sns_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_2_NUM 3u
#define CapSense_Sns_2_PORT GPIO_PRT8
#define CapSense_Sns_2_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_3_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_3_INBUF_ENABLED 0u
#define CapSense_Sns_3_INIT_DRIVESTATE 1u
#define CapSense_Sns_3_INIT_MUXSEL 0u
#define CapSense_Sns_3_INPUT_SYNC 2u
#define CapSense_Sns_3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_3_NUM 4u
#define CapSense_Sns_3_PORT GPIO_PRT8
#define CapSense_Sns_3_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_4_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_4_INBUF_ENABLED 0u
#define CapSense_Sns_4_INIT_DRIVESTATE 1u
#define CapSense_Sns_4_INIT_MUXSEL 0u
#define CapSense_Sns_4_INPUT_SYNC 2u
#define CapSense_Sns_4_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_4_NUM 5u
#define CapSense_Sns_4_PORT GPIO_PRT8
#define CapSense_Sns_4_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_4_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_5_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_5_INBUF_ENABLED 0u
#define CapSense_Sns_5_INIT_DRIVESTATE 1u
#define CapSense_Sns_5_INIT_MUXSEL 0u
#define CapSense_Sns_5_INPUT_SYNC 2u
#define CapSense_Sns_5_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_5_NUM 6u
#define CapSense_Sns_5_PORT GPIO_PRT8
#define CapSense_Sns_5_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_5_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_6_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_6_INBUF_ENABLED 0u
#define CapSense_Sns_6_INIT_DRIVESTATE 1u
#define CapSense_Sns_6_INIT_MUXSEL 0u
#define CapSense_Sns_6_INPUT_SYNC 2u
#define CapSense_Sns_6_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_6_NUM 7u
#define CapSense_Sns_6_PORT GPIO_PRT8
#define CapSense_Sns_6_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_6_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Cmod */
#define CapSense_Cmod_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_0_INBUF_ENABLED 0u
#define CapSense_Cmod_0_INIT_DRIVESTATE 1u
#define CapSense_Cmod_0_INIT_MUXSEL 0u
#define CapSense_Cmod_0_INPUT_SYNC 2u
#define CapSense_Cmod_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_0_NUM 1u
#define CapSense_Cmod_0_PORT GPIO_PRT7
#define CapSense_Cmod_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Cmod_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_INBUF_ENABLED 0u
#define CapSense_Cmod_INIT_DRIVESTATE 1u
#define CapSense_Cmod_INIT_MUXSEL 0u
#define CapSense_Cmod_INPUT_SYNC 2u
#define CapSense_Cmod_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_NUM 1u
#define CapSense_Cmod_PORT GPIO_PRT7
#define CapSense_Cmod_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Shield */
#define CapSense_Shield_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Shield_0_INBUF_ENABLED 0u
#define CapSense_Shield_0_INIT_DRIVESTATE 1u
#define CapSense_Shield_0_INIT_MUXSEL 0u
#define CapSense_Shield_0_INPUT_SYNC 2u
#define CapSense_Shield_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Shield_0_NUM 0u
#define CapSense_Shield_0_PORT GPIO_PRT1
#define CapSense_Shield_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Shield_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Shield_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Shield_INBUF_ENABLED 0u
#define CapSense_Shield_INIT_DRIVESTATE 1u
#define CapSense_Shield_INIT_MUXSEL 0u
#define CapSense_Shield_INPUT_SYNC 2u
#define CapSense_Shield_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Shield_NUM 0u
#define CapSense_Shield_PORT GPIO_PRT1
#define CapSense_Shield_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Shield_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
