/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* Timer_Int */
#define Timer_Int__INTC_CORTEXM4_ASSIGNED 1
#define Timer_Int__INTC_CORTEXM4_PRIORITY 7u
#define Timer_Int__INTC_NUMBER 19u
#define Timer_Int_INTC_CORTEXM4_ASSIGNED 1
#define Timer_Int_INTC_CORTEXM4_PRIORITY 7u
#define Timer_Int_INTC_NUMBER 19u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr__INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr_INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr_INTC_NUMBER 24u

/* XBEE_UART_SCB_IRQ */
#define XBEE_UART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define XBEE_UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define XBEE_UART_SCB_IRQ__INTC_NUMBER 46u
#define XBEE_UART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define XBEE_UART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define XBEE_UART_SCB_IRQ_INTC_NUMBER 46u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
