/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_CM0p_Reading */
#define Pin_CM0p_Reading_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM0p_Reading_0_INBUF_ENABLED 0u
#define Pin_CM0p_Reading_0_INIT_DRIVESTATE 0u
#define Pin_CM0p_Reading_0_INIT_MUXSEL 0u
#define Pin_CM0p_Reading_0_INPUT_SYNC 2u
#define Pin_CM0p_Reading_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM0p_Reading_0_NUM 0u
#define Pin_CM0p_Reading_0_PORT GPIO_PRT5
#define Pin_CM0p_Reading_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM0p_Reading_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_CM0p_Reading_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM0p_Reading_INBUF_ENABLED 0u
#define Pin_CM0p_Reading_INIT_DRIVESTATE 0u
#define Pin_CM0p_Reading_INIT_MUXSEL 0u
#define Pin_CM0p_Reading_INPUT_SYNC 2u
#define Pin_CM0p_Reading_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM0p_Reading_NUM 0u
#define Pin_CM0p_Reading_PORT GPIO_PRT5
#define Pin_CM0p_Reading_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM0p_Reading_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_CM0p_Writing */
#define Pin_CM0p_Writing_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM0p_Writing_0_INBUF_ENABLED 0u
#define Pin_CM0p_Writing_0_INIT_DRIVESTATE 0u
#define Pin_CM0p_Writing_0_INIT_MUXSEL 0u
#define Pin_CM0p_Writing_0_INPUT_SYNC 2u
#define Pin_CM0p_Writing_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM0p_Writing_0_NUM 1u
#define Pin_CM0p_Writing_0_PORT GPIO_PRT5
#define Pin_CM0p_Writing_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM0p_Writing_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_CM0p_Writing_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM0p_Writing_INBUF_ENABLED 0u
#define Pin_CM0p_Writing_INIT_DRIVESTATE 0u
#define Pin_CM0p_Writing_INIT_MUXSEL 0u
#define Pin_CM0p_Writing_INPUT_SYNC 2u
#define Pin_CM0p_Writing_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM0p_Writing_NUM 1u
#define Pin_CM0p_Writing_PORT GPIO_PRT5
#define Pin_CM0p_Writing_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM0p_Writing_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_CM4_Reading */
#define Pin_CM4_Reading_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM4_Reading_0_INBUF_ENABLED 0u
#define Pin_CM4_Reading_0_INIT_DRIVESTATE 0u
#define Pin_CM4_Reading_0_INIT_MUXSEL 0u
#define Pin_CM4_Reading_0_INPUT_SYNC 2u
#define Pin_CM4_Reading_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM4_Reading_0_NUM 2u
#define Pin_CM4_Reading_0_PORT GPIO_PRT5
#define Pin_CM4_Reading_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM4_Reading_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_CM4_Reading_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM4_Reading_INBUF_ENABLED 0u
#define Pin_CM4_Reading_INIT_DRIVESTATE 0u
#define Pin_CM4_Reading_INIT_MUXSEL 0u
#define Pin_CM4_Reading_INPUT_SYNC 2u
#define Pin_CM4_Reading_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM4_Reading_NUM 2u
#define Pin_CM4_Reading_PORT GPIO_PRT5
#define Pin_CM4_Reading_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM4_Reading_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_CM4_Writing */
#define Pin_CM4_Writing_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM4_Writing_0_INBUF_ENABLED 0u
#define Pin_CM4_Writing_0_INIT_DRIVESTATE 0u
#define Pin_CM4_Writing_0_INIT_MUXSEL 0u
#define Pin_CM4_Writing_0_INPUT_SYNC 2u
#define Pin_CM4_Writing_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM4_Writing_0_NUM 3u
#define Pin_CM4_Writing_0_PORT GPIO_PRT5
#define Pin_CM4_Writing_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM4_Writing_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_CM4_Writing_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM4_Writing_INBUF_ENABLED 0u
#define Pin_CM4_Writing_INIT_DRIVESTATE 0u
#define Pin_CM4_Writing_INIT_MUXSEL 0u
#define Pin_CM4_Writing_INPUT_SYNC 2u
#define Pin_CM4_Writing_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM4_Writing_NUM 3u
#define Pin_CM4_Writing_PORT GPIO_PRT5
#define Pin_CM4_Writing_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM4_Writing_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
